apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-persistent-volume
  labels:
    type: local
    size: small

# Estado deseado del recurso Persisten Volume
spec:

  # solicitud de espacio
  capacity:
    storage: 10Gi

  # un único nodo del cluster podrá tener access de lectura-escritura
  accessModes:
    - ReadWriteOnce

  # Indica en donde el volumen será montado dentro del espacio virtual del cluster
  # El directorio indicado en ésta sección, es el valor default the la imagen de docker "mysql"
  # Este es el directorio fisico del host (en este caso, estamos usando el modo hostPath) de sistema de volumenes
  hostPath:
    path: "/var/lib/mysql"
